import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Card from 'react-bootstrap/Card';
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';

const cardContent = [
  {
    "title": "Scroll Infinito",
    "subtitle": "4/09/2022",
    "text": "Exemplo de aplicaçao do scroll infinito em React",
    "link": {
      "linkName": "Scroll Infinito",
      "linkAddress": "/examples/scrollInfinito"
    }
  },
  {
    "title": "Card1",
    "subtitle": "4/09/2022",
    "text": "",
    "link": {
      "linkName": "",
      "linkAddress": ""
    }
  },
]

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Next.js / React Playground</h1>

        <Container>
          <Row>


            {
              cardContent.map(item => {
                return (
                  <Col key={item.link.linkAddress}>
                    <Card style={{ width: '18rem' }}>
                      <Card.Body>
                        <Card.Title>{item.title}</Card.Title>
                        <Card.Subtitle className="mb-2 text-muted">{item.subtitle}</Card.Subtitle>
                        <Card.Text>{item.text}
                        </Card.Text>
                        <Card.Link href={item.link.linkAddress}>{item.link.linkName}</Card.Link>
                      </Card.Body>
                    </Card>
                  </Col>
                )
              })
            }

          </Row>
        </Container>
      </main>

    </div>
  )
}

export default Home
